### ISSUE TITLE
Page animation inconsistency

### ISSUE THREAD

**Issue by misha130** [codidact/co-design#1]
#### Short description of the problem:
When you open a page there is a transform on the logo and the button that extends.
Sometimes this also happens when you are switching tabs

#### What behavior are you expecting?
The animation to always happen, to not happen, or to not affect the logo.

**Steps to reproduce:**
1. Open web site
2. Switch tabs to see if animations happens

Video: 
https://i.gyazo.com/2eeb8032a63c69f51fc022c570e94fd9.mp4

**Comment by luap42** [comment]
This seems to be a caching-related Chrome issue. Can you confirm, that this only happens in Chrome and only, when you load the page for the first time in a while?

It seems to be a [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content).

**Comment by misha130** [comment]
Not sure, I tested it on Firefox too and saw it. 
But I think it is a cache related issue.
Sometimes I minimize the tab for like 10 minutes and then start clicking tabs in the website and it plays the transform.
I couldn't get a gif of that though since it sort of stops after like 3 animations.

**Comment by luap42** [comment]
This doesn't look like it can be reproduced anymore. Can you still reproduce this on the official documentation on https://design.codidact.org?

**Comment by misha130** [comment]
Yes, now its fine.I remember seeing it two weeks ago though but I think its fine now.
