### ISSUE TITLE
Should we have a footer, how should it look like?

### ISSUE THREAD

**Issue by luap42** [codidact/co-design#14]
I think we should have a native footer component in Co-Design. Currently, Codidact uses some utility classes to style this, which is sub-ideal:

https://github.com/codidact/core/pull/13#discussion_r367250464

There are two ways to have a footer IMO:

- more minimal (license notice, link to important policy and maybe instance master)
- more complex, similar to Stack Exchange

What do you think? Which way should we design for?

**Comment by ArtOfCode-** [comment]
I'd probably go minimal, but as long as it has the important information clearly in it, it won't matter too much.

**Comment by roberrrt-s** [comment]
My two cents: Whenever the need arises for such a compenent, it should be implemented. Just basic, important information / navigation for now would be fine, yes?
