### ISSUE TITLE
Replace BAT file with Node or Shell script

### ISSUE THREAD

**Issue by hilts-vaughan** [codidact/co-design#15]
You can run the other components on Linux (the core) but you can't compile the co-design framework on Linux with the script. You can version your compiler (scss) with `node` as well so we should probably do that.

Happy to write the PR if you would like.

**Comment by luap42** [comment]
That's not true. Anyone can build Co-Design on any reasonable computer. It's just that the build scripts for Windows are in the repo, because I use Windows and I initialized the Co-Design framework. 

I'd oppose removing the windows scripts, but instead I suggest, to add the Linux scripts, too.

**Comment by hilts-vaughan** [comment]
Sorry, it was not clear.. _with the script_ is the keyword. Of course you can run SASS as-is.

I'm proposing to just replace the entire thing with a `package.json`

```
scripts: {
   build: npx sass ... OR ./node_modules/sass
}
```

.. with NPX. This is much better than relying on a global compiler, which may or may not be up to date and people may or may not be running different versions.

Also, it's cross platform.

**Comment by luap42** [comment]
Completed.
