### ISSUE TITLE
No fallback font

### ISSUE THREAD

**Issue by appgurueu** [codidact/co-design#17]
By looking at the [fontface](https://github.com/codidact/co-design/blob/develop/src/_fontface.scss) code, I see that there is no fallback font if Red Hat Display fails to provide certain characters.

**Comment by luap42** [comment]
Aren't the fallback fonts defined in the _config.scss? (lines 1 and 2)

https://github.com/codidact/co-design/blob/develop/src/_config.scss#L2

**Comment by appgurueu** [comment]
I didn't see them (they should probably be in _fontface.scss?) but yes, they are mostly sufficient. See https://jlericson.com/2018/12/17/tony_the_pony.html.

**Comment by luap42** [comment]
Okay. I am closing this then. The fontface file is for importing the font, whereas they are applied in the typography file.
