### ISSUE TITLE
Set breakpoints in px, contract mobile break width

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/co-design#25]
Picked up in the recent QPixel changes.

Breakpoints are generally better set in pixels than in `em`; pixels are a device measurement, whereas `em` is based on font size, which may change.

We should also expand the "mobile" level break. Moving into a hamburger menu on a tablet is okay, but should not be happening on just a small desktop window. I'd suggest we don't consider a page "mobile" (and thus hamburger-ify it) until around ~850px. QPixel can go down to 820px before there's not enough space for the stuff in the header.

**Comment by luap42** [comment]
Completed with 850px for header breakpoint; can be changed in _config.scss.
