### ISSUE TITLE
Provide a tab-styled version of the tabs component

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/co-design#30]
The current tabs component is styled to look like buttons. That's fine in most contexts, but some contexts need something that looks like traditional tabs (I'm thinking in particular of a navigational header). Can we either add a new component for that, or a `.tabs.is-tab-style` (or equivalent) to get some traditional tabs?

**Comment by luap42** [comment]
As a suggestion, would having simply a line below the "buttons" enough for the tab presentation. I can create a view, where we have a top line, which is interrupted on the active tab, but it'd be more hacky probably and I'd like to avoid that:

![Example for the traditional tabs](https://user-images.githubusercontent.com/21335202/79107765-44f87280-7d75-11ea-8261-eafe051b310c.png)

(Activity is active, Mod has hover)

**Comment by ArtOfCode-** [comment]
That... would work just fine, actually.
