### ISSUE TITLE
Modals sometimes won't open (rather they open and immediately close)

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/co-design#72]
Sometimes modals don't seem to open when their trigger is click on. This is due to the following lines in the handler for clicking outside the modal: 

https://github.com/codidact/co-design/blob/8ccc296529f0d56c3ecab697241aa5daba3eaa08/js_src/header.ts#L76-L78
https://github.com/codidact/co-design/blob/8ccc296529f0d56c3ecab697241aa5daba3eaa08/js_src/droppanel.ts#L85-L87

Note the check for `this.panelTriggerNode !== target`. Consider the following layout:

```
<trigger element>
  <sub element>
<trigger element>
<modal popout element>
```

When `<sub element>` is clicked on, the modal is opened. However, since the trigger is outside the modal, the `closeXOnClickOutside` handler is also called - and since `sub element !== trigger element`, it immediately closes the modal again

The solution for both modal types is to replace `_this.XTriggerNode !== target` with `!this.XTriggerNode.contains(target)`.

**Comment by cellio** [comment]
Has this change been propagated to qpixel yet?
