### ISSUE TITLE
Build instructions differ between readme and guide

### ISSUE THREAD

**Issue by trichoplax** [codidact/co-design#82]
**Describe the bug**
The instructions in this repo's readme are different from the instructions in the guide that the readme links to.

Readme build instructions:
- `npm run build`

Installation guide build instructions:
- `~/co-design $ npm run build`
- `~/co-design $ npm run js_build`

Should the extra `npm run js_build` be added to the readme or removed from the installation guide?

**Comment by trichoplax** [comment]
It appears that `js_build` also calls `build` as its final step. Is `build` redundant if immediately followed by `js_build`?

In addition to the 2 places I mentioned in this issue, the `build` followed by `js_build` is also present in https://design.codidact.org/setup/improving/ so maybe we could make all 3 places consistent (or add explanations if they shouldn't be).

**Comment by cellio** [comment]
Or does `js_build` depend on some `build` outputs (and then produce more)?  This will require more digging/experimentation.
