### ISSUE TITLE
Close button is off (a very little tiny bit)

### ISSUE THREAD

**Issue by alexlya** [codidact/co-design#9]
Close button on alert is a bit off:

![image](https://user-images.githubusercontent.com/23587065/72019898-720f2380-3262-11ea-934a-51e029c58e79.png)

and removing that css style snaps it back in place:

![image](https://user-images.githubusercontent.com/23587065/72019987-a84ca300-3262-11ea-99c5-4ead047cefd8.png)

**Comment by ArtOfCode-** [comment]
Once you've removed that style, what `margin-top` is active? The Computed tab might show you, if you're not sure.

**Comment by luap42** [comment]
There's already a pull request for this: #8 

Quoting from there:

> This issue was introduced in dda9ccc. I intended to remove the margin around p and hX elements for design reasons. I am not sure, whether forcing this here is the best option, or whether it would be better to except close buttons from the check (and applying it to the element after it, instead).

And this proposed solution:

> What might be better would be to re-apply the `margin-top: -$padding-unit;` if it is the close button in a notice and the first child (`.notice .is-close-button:first-child`). This prevents using the hard-to-override !important flag.

I am currently waiting for @jcfoxtrot54 to reply and update their PR. If that doesn't happen in a few days, I'll go ahead and make the change.

**Comment by luap42** [comment]
@ArtOfCode- There should be the default style for `.notice .is-close-button` then that applies the top margin (-1 margin units). However that is overriden by a `.notice :first-child { margin-top: 0 }` code.

**Comment by jcfoxtrot54** [comment]
@luap42 Hiya, really sorry but I've been swamped with work. If you want to make the change, feel free. If not I'll try and get around to it later today.

**Comment by luap42** [comment]
@jcfoxtrot54 Okay, if it is not a problem for you, I'll do it.

**Comment by luap42** [comment]
Closed in 98b6c84
